In [1]:
import torch
import torch.nn as nn
from collections import OrderedDict
model = nn.Linear(2, 4, True)
np = model.named_parameters()

In [2]:
param_dict = {n:p for n,p in model.named_parameters()}
ordered_dict = OrderedDict(model.named_parameters())

In [ ]:
for n, p in param_dict.items():
    print(n, p)

for n, p in ordered_dict.items():
    print(n, p)
    if ordered_dict[n].requires_grad:
        print ("this thing requires grad") 

weight Parameter containing:
tensor([[ 0.4793, -0.6502],
        [ 0.5793,  0.0958],
        [-0.7064, -0.5184],
        [ 0.2039, -0.3985]], requires_grad=True)
bias Parameter containing:
tensor([ 0.5365, -0.2122,  0.5024, -0.2950], requires_grad=True)
weight Parameter containing:
tensor([[ 0.4793, -0.6502],
        [ 0.5793,  0.0958],
        [-0.7064, -0.5184],
        [ 0.2039, -0.3985]], requires_grad=True)
this thing requires grad
bias Parameter containing:
tensor([ 0.5365, -0.2122,  0.5024, -0.2950], requires_grad=True)
this thing requires grad


In [28]:
with torch.no_grad():
    param_dict["weight"].add_(1, alpha=1)

In [29]:
param_dict["weight"]

Parameter containing:
tensor([[-0.4455, -0.1036],
        [ 3.4462,  3.1909],
        [ 0.4231,  0.5255],
        [ 3.2258, -1.1044]], requires_grad=True)

In [20]:
rank = False

master_process = True if rank else rank

In [21]:
master_process

False